version: '3.7'

services:
  jsonapi:
    container_name: jsonapi
    image: carlonicora/jsonapi:3.0
    build:
      context: .
      dockerfile: ./php-cli/Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
    tty: true
    stdin_open: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora